sudo: false
dist: trusty
language: cpp

compiler:
  - clang

addons:
  apt:
    packages:
      - g++-6
      - cmake
      - build-essential
      - cppcheck
      - git
      - make
      - openssl
      - libssl-dev
      - libmysqlclient-dev
      - libreadline6-dev
      - zlib1g-dev
      - zip
      - unzip

git:
  depth: 1
      
before_install:
  - sudo apt-get -qq install libace-dev

install:
  - mkdir build
  - cd build
  - cmake .. -DSERVERS=1 -DTOOLS=1 -DSCRIPTS=1 -DWITH_WARNINGS=1 -DWITH_COREDEBUG=0
  - make -j2
