dist: precise
language: cpp
compiler:
  - clang

git:
  depth: 1

sudo: false

os:
  - linux


addons:
  apt:
    sources:
      - kubuntu-backports
      - ubuntu-toolchain-r-test
  apt:
    packages:
      - cmake
      - build-essential
      - cppcheck
      - git
      - make
      - openssl
      - libssl-dev
      - binutils-dev
      - zlib1g-dev
      - zip
      - unzip
      - php5-cli
      - php5-mysql
      
before_install:
  - sudo apt-get -qq install libace-dev

install:
  - mkdir build
  - cd build
  - cmake .. -DSERVERS=1 -DTOOLS=1 -DSCRIPTS=1 -DWITH_WARNINGS=1 -DWITH_COREDEBUG=0
# we have 1.5 cpu so 2 jobs at a time are sufficient
  - make -j2
