sudo: false
dist: trusty
language: cpp

compiler:
  - clang

addons:
  apt:
    sources:
      - ubuntu-toolchain-r-test
    packages:
      - cmake
      - cppcheck
      - git
      - openssl
      - libssl-dev
      - libmysqlclient-dev
      - libreadline6-dev
      - zlib1g-dev
      - unzip

git:
  depth: 1
      
before_install:
  - sudo apt-get -qq install libace-dev binutils-2.26-dev
  - export PATH=/usr/lib/binutils-2.26/bin:${PATH}

install:
  - mkdir build
  - cd build
  - cmake .. -DSERVERS=1 -DTOOLS=1 -DSCRIPTS=1 -DWITH_WARNINGS=1 -DWITH_COREDEBUG=0

script:
  - make -j 4 -k
